INSERT INTO CUSTOMER (ID, NAME) VALUES (1, 'Acme GmbH');
INSERT INTO CUSTOMER (ID, NAME) VALUES (2, 'Globex AG');

INSERT INTO RATE (ID, CUSTOMER_ID, RATE, FROM_DATE, TO_DATE) VALUES (1, 1, 85.0, CURRENT_DATE, NULL);
INSERT INTO RATE (ID, CUSTOMER_ID, RATE, FROM_DATE, TO_DATE) VALUES (2, 2, 95.0, CURRENT_DATE, NULL);

INSERT INTO PROJECT (ID, TITLE, SUB_TITLE, CUSTOMER_ID, ACTIVE, BILLABLE, PRIORITY)
VALUES (1, 'CRM Migration', 'Phase 1', 1, TRUE, TRUE, 1);

INSERT INTO PROJECT (ID, TITLE, SUB_TITLE, CUSTOMER_ID, ACTIVE, BILLABLE, PRIORITY)
VALUES (2, 'Web Portal', 'Pilotprojekt', 2, TRUE, TRUE, 2);

INSERT INTO BOOKING (ID, PROJECT_ID, FROM_DATE, TO_DATE, MINUTES, BREAK_MINUTES, BILLABLE, NOTE)
VALUES (1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 480, 30, TRUE, 'Initial setup work');

INSERT INTO BOOKING (ID, PROJECT_ID, FROM_DATE, TO_DATE, MINUTES, BREAK_MINUTES, BILLABLE, NOTE)
VALUES (2, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 300, 15, TRUE, 'Frontend adjustments');
